package com.example.groot.utility

object LanguageData {

    val extensions = mapOf(
        ".bsl" to "1C Enterprise",
        ".os" to "1C Enterprise",
        ".4dm" to "4D",
        ".abap" to "ABAP",
        ".asddls" to "ABAP CDS",
        ".asc" to "AGS Script",
        ".ash" to "AGS Script",
        ".aidl" to "AIDL",
        ".al" to "Perl",
        ".ampl" to "AMPL",
        ".mod" to "NMODL",
        ".g4" to "ANTLR",
        ".apl" to "APL",
        ".dyalog" to "APL",
        ".asax" to "ASP.NET",
        ".ascx" to "ASP.NET",
        ".ashx" to "ASP.NET",
        ".asmx" to "ASP.NET",
        ".aspx" to "ASP.NET",
        ".axd" to "ASP.NET",
        ".dats" to "ATS",
        ".hats" to "ATS",
        ".sats" to "ATS",
        ".as" to "AngelScript",
        ".adb" to "Ada",
        ".ada" to "Ada",
        ".ads" to "Ada",
        ".agda" to "Agda",
        ".als" to "Alloy",
        ".angelscript" to "AngelScript",
        ".cls" to "Visual Basic 6.0",
        ".trigger" to "Shell",
        ".agc" to "Apollo Guidance Computer",
        ".applescript" to "AppleScript",
        ".scpt" to "AppleScript",
        ".arc" to "Arc",
        ".aj" to "AspectJ",
        ".asm" to "Motorola 68K Assembly",
        ".a51" to "Assembly",
        ".i" to "Motorola 68K Assembly",
        ".inc" to "SourcePawn",
        ".nas" to "Nasal",
        ".nasm" to "Assembly",
        ".asy" to "Asymptote",
        ".aug" to "Augeas",
        ".ahk" to "AutoHotkey",
        ".ahkl" to "AutoHotkey",
        ".au3" to "AutoIt",
        ".awk" to "Awk",
        ".auk" to "Awk",
        ".gawk" to "Awk",
        ".mawk" to "Awk",
        ".nawk" to "Awk",
        ".bas" to "Visual Basic 6.0",
        ".bqn" to "BQN",
        ".bal" to "Ballerina",
        ".bat" to "Batchfile",
        ".cmd" to "Batchfile",
        ".bf" to "Brainfuck",
        ".be" to "Berry",
        ".bicep" to "Bicep",
        ".bicepparam" to "Bicep",
        ".bison" to "Bison",
        ".bb" to "Clojure",
        ".bbappend" to "BitBake",
        ".bbclass" to "BitBake",
        ".decls" to "BlitzBasic",
        ".bmx" to "BlitzMax",
        ".bsv" to "Bluespec",
        ".bs" to "BrighterScript",
        ".boo" to "Boo",
        ".bpl" to "Boogie",
        ".b" to "Brainfuck",
        ".brs" to "Brightscript",
        ".c" to "C",
        ".cats" to "C",
        ".h" to "Objective-C",
        ".idc" to "C",
        ".cs" to "Smalltalk",
        ".cake" to "CoffeeScript",
        ".cs.pp" to "C#",
        ".csx" to "C#",
        ".linq" to "C#",
        ".cpp" to "C++",
        ".c++" to "C++",
        ".cc" to "C++",
        ".cp" to "Component Pascal",
        ".cppm" to "C++",
        ".cxx" to "C++",
        ".h++" to "C++",
        ".hh" to "Hack",
        ".hpp" to "C++",
        ".hxx" to "C++",
        ".inl" to "C++",
        ".ino" to "C++",
        ".ipp" to "C++",
        ".ixx" to "C++",
        ".re" to "Reason",
        ".tcc" to "C++",
        ".tpp" to "C++",
        ".txx" to "C++",
        ".cds" to "CAP CDS",
        ".clp" to "CLIPS",
        ".cmake" to "CMake",
        ".cmake.in" to "CMake",
        ".cue" to "CUE",
        ".w" to "OpenEdge ABL",
        ".cdc" to "Cadence",
        ".cairo" to "Cairo Zero",
        ".mligo" to "CameLIGO",
        ".capnp" to "Cap'n Proto",
        ".carbon" to "Carbon",
        ".ceylon" to "Ceylon",
        ".chpl" to "Chapel",
        ".ck" to "ChucK",
        ".circom" to "Circom",
        ".cirru" to "Cirru",
        ".clw" to "Clarion",
        ".clar" to "Clarity",
        ".asp" to "Classic ASP",
        ".icl" to "Clean",
        ".dcl" to "Clean",
        ".click" to "Click",
        ".clj" to "Clojure",
        ".boot" to "Clojure",
        ".cl2" to "Clojure",
        ".cljc" to "Clojure",
        ".cljs" to "Clojure",
        ".cljs.hl" to "Clojure",
        ".cljscm" to "Clojure",
        ".cljx" to "Clojure",
        ".hic" to "Clojure",
        ".ql" to "CodeQL",
        ".qll" to "CodeQL",
        ".coffee" to "CoffeeScript",
        "._coffee" to "CoffeeScript",
        ".cjsx" to "CoffeeScript",
        ".iced" to "CoffeeScript",
        ".cfm" to "ColdFusion",
        ".cfml" to "ColdFusion",
        ".cfc" to "ColdFusion CFC",
        ".lisp" to "NewLisp",
        ".asd" to "Common Lisp",
        ".cl" to "OpenCL",
        ".l" to "PicoLisp",
        ".lsp" to "NewLisp",
        ".ny" to "Common Lisp",
        ".podsl" to "Common Lisp",
        ".sexp" to "Common Lisp",
        ".cwl" to "Common Workflow Language",
        ".cps" to "Component Pascal",
        ".coq" to "Coq",
        ".v" to "Verilog",
        ".cr" to "Crystal",
        ".orc" to "Csound",
        ".udo" to "Csound",
        ".csd" to "Csound Document",
        ".sco" to "Csound Score",
        ".cu" to "Cuda",
        ".cuh" to "Cuda",
        ".curry" to "Curry",
        ".cyp" to "Cypher",
        ".cypher" to "Cypher",
        ".pyx" to "Cython",
        ".pxd" to "Cython",
        ".pxi" to "Cython",
        ".d" to "Makefile",
        ".di" to "D",
        ".dm" to "DM",
        ".dfy" to "Dafny",
        ".dart" to "Dart",
        ".dwl" to "DataWeave",
        ".dsc" to "DenizenScript",
        ".dhall" to "Dhall",
        ".dockerfile" to "Dockerfile",
        ".djs" to "Dogescript",
        ".dylan" to "Dylan",
        ".dyl" to "Dylan",
        ".intr" to "Dylan",
        ".lid" to "Dylan",
        ".e" to "Euphoria",
        ".ecl" to "ECLiPSe",
        ".eclxml" to "ECL",
        ".eq" to "EQ",
        ".edgeql" to "EdgeQL",
        ".esdl" to "EdgeQL",
        ".ex" to "Euphoria",
        ".exs" to "Elixir",
        ".elm" to "Elm",
        ".elv" to "Elvish",
        ".el" to "Emacs Lisp",
        ".emacs" to "Emacs Lisp",
        ".emacs.desktop" to "Emacs Lisp",
        ".em" to "EmberScript",
        ".emberscript" to "EmberScript",
        ".erl" to "Erlang",
        ".app" to "Erlang",
        ".app.src" to "Erlang",
        ".es" to "JavaScript",
        ".escript" to "Erlang",
        ".hrl" to "Erlang",
        ".xrl" to "Erlang",
        ".yrl" to "Erlang",
        ".fs" to "GLSL",
        ".fsi" to "F#",
        ".fsx" to "F#",
        ".fst" to "F*",
        ".fsti" to "F*",
        ".fir" to "FIRRTL",
        ".fx" to "HLSL",
        ".flux" to "FLUX",
        ".factor" to "Factor",
        ".fy" to "Fancy",
        ".fancypack" to "Fancy",
        ".fan" to "Fantom",
        ".dsp" to "Faust",
        ".fnl" to "Fennel",
        ".f" to "Fortran",
        ".ftl" to "FreeMarker",
        ".fth" to "Forth",
        ".4th" to "Forth",
        ".for" to "Fortran",
        ".forth" to "Forth",
        ".fr" to "Frege",
        ".frt" to "Forth",
        ".f77" to "Fortran",
        ".fpp" to "Fortran",
        ".f90" to "Fortran Free Form",
        ".f03" to "Fortran Free Form",
        ".f08" to "Fortran Free Form",
        ".f95" to "Fortran Free Form",
        ".bi" to "FreeBasic",
        ".fut" to "Futhark",
        ".g" to "GAP",
        ".cnc" to "G-code",
        ".gco" to "G-code",
        ".gcode" to "G-code",
        ".gaml" to "GAML",
        ".gms" to "GAMS",
        ".gap" to "GAP",
        ".gd" to "GDScript",
        ".gi" to "GAP",
        ".tst" to "Scilab",
        ".md" to "GCC Machine Description",
        ".glsl" to "GLSL",
        ".fp" to "GLSL",
        ".frag" to "JavaScript",
        ".frg" to "GLSL",
        ".fsh" to "GLSL",
        ".fshader" to "GLSL",
        ".geo" to "GLSL",
        ".geom" to "GLSL",
        ".glslf" to "GLSL",
        ".glslv" to "GLSL",
        ".gs" to "JavaScript",
        ".gshader" to "GLSL",
        ".rchit" to "GLSL",
        ".rmiss" to "GLSL",
        ".shader" to "ShaderLab",
        ".tesc" to "GLSL",
        ".tese" to "GLSL",
        ".vert" to "GLSL",
        ".vrx" to "GLSL",
        ".vs" to "GLSL",
        ".vsh" to "GLSL",
        ".vshader" to "GLSL",
        ".gsc" to "GSC",
        ".csc" to "GSC",
        ".gsh" to "GSC",
        ".gml" to "Game Maker Language",
        ".4gl" to "Genero 4gl",
        ".kid" to "Genshi",
        ".ebuild" to "Gentoo Ebuild",
        ".eclass" to "Gentoo Eclass",
        ".feature" to "Gherkin",
        ".story" to "Gherkin",
        ".gleam" to "Gleam",
        ".gjs" to "Glimmer JS",
        ".gts" to "Glimmer TS",
        ".glf" to "Glyph",
        ".gp" to "Gnuplot",
        ".gnu" to "Gnuplot",
        ".gnuplot" to "Gnuplot",
        ".p" to "OpenEdge ABL",
        ".plot" to "Gnuplot",
        ".plt" to "Prolog",
        ".go" to "Go",
        ".golo" to "Golo",
        ".gst" to "Gosu",
        ".gsx" to "Gosu",
        ".vark" to "Gosu",
        ".grace" to "Grace",
        ".gf" to "Grammatical Framework",
        ".groovy" to "Groovy",
        ".grt" to "Groovy",
        ".gtpl" to "Groovy",
        ".gvy" to "Groovy",
        ".gsp" to "Groovy Server Pages",
        ".hcl" to "HCL",
        ".nomad" to "HCL",
        ".tf" to "HCL",
        ".tfvars" to "HCL",
        ".workflow" to "HCL",
        ".hlsl" to "HLSL",
        ".cginc" to "HLSL",
        ".fxh" to "HLSL",
        ".hlsli" to "HLSL",
        ".hack" to "Hack",
        ".hhi" to "Hack",
        ".php" to "PHP",
        ".hb" to "Harbour",
        ".hs" to "Haskell",
        ".hs-boot" to "Haskell",
        ".hsc" to "Haskell",
        ".hx" to "Haxe",
        ".hxsl" to "Haxe",
        ".q" to "q",
        ".hql" to "HiveQL",
        ".hc" to "HolyC",
        ".hy" to "Hy",
        ".pro" to "Prolog",
        ".dlm" to "IDL",
        ".ipf" to "IGOR Pro",
        ".idr" to "Idris",
        ".lidr" to "Idris",
        ".ijm" to "ImageJ Macro",
        ".imba" to "Imba",
        ".iss" to "Inno Setup",
        ".isl" to "Inno Setup",
        ".io" to "Io",
        ".ik" to "Ioke",
        ".thy" to "Isabelle",
        ".ijs" to "J",
        ".jcl" to "JCL",
        ".flex" to "JFlex",
        ".jflex" to "JFlex",
        ".jq" to "jq",
        ".janet" to "Janet",
        ".j" to "Objective-J",
        ".java" to "Java",
        ".jav" to "Java",
        ".jsh" to "Java",
        ".jsp" to "Java Server Pages",
        ".tag" to "Java Server Pages",
        ".jte" to "Java Template Engine",
        ".js" to "JavaScript",
        "._js" to "JavaScript",
        ".bones" to "JavaScript",
        ".cjs" to "JavaScript",
        ".es6" to "JavaScript",
        ".jake" to "JavaScript",
        ".javascript" to "JavaScript",
        ".jsb" to "JavaScript",
        ".jscad" to "JavaScript",
        ".jsfl" to "JavaScript",
        ".jslib" to "JavaScript",
        ".jsm" to "JavaScript",
        ".jspre" to "JavaScript",
        ".jss" to "JavaScript",
        ".jsx" to "JavaScript",
        ".mjs" to "JavaScript",
        ".njs" to "JavaScript",
        ".pac" to "JavaScript",
        ".sjs" to "JavaScript",
        ".ssjs" to "JavaScript",
        ".xsjs" to "JavaScript",
        ".xsjslib" to "JavaScript",
        ".js.erb" to "JavaScript+ERB",
        ".mps" to "JetBrains MPS",
        ".mpl" to "JetBrains MPS",
        ".msd" to "JetBrains MPS",
        ".jison" to "Jison",
        ".jisonlex" to "Jison Lex",
        ".ol" to "Jolie",
        ".iol" to "Jolie",
        ".jsonnet" to "Jsonnet",
        ".libsonnet" to "Jsonnet",
        ".jl" to "Julia",
        ".just" to "Just",
        ".krl" to "KRL",
        ".ksy" to "Kaitai Struct",
        ".kak" to "KakouneScript",
        ".ks" to "KerboScript",
        ".kt" to "Kotlin",
        ".ktm" to "Kotlin",
        ".kts" to "Kotlin",
        ".lfe" to "LFE",
        ".ll" to "LLVM",
        ".lol" to "LOLCODE",
        ".lsl" to "LSL",
        ".lslp" to "LSL",
        ".lvproj" to "LabVIEW",
        ".lvclass" to "LabVIEW",
        ".lvlib" to "LabVIEW",
        ".lasso" to "Lasso",
        ".las" to "Lasso",
        ".lasso8" to "Lasso",
        ".lasso9" to "Lasso",
        ".lex" to "Lex",
        ".ligo" to "LigoLANG",
        ".ly" to "LilyPond",
        ".ily" to "LilyPond",
        ".lagda" to "Literate Agda",
        ".litcoffee" to "Literate CoffeeScript",
        ".coffee.md" to "Literate CoffeeScript",
        ".lhs" to "Literate Haskell",
        ".livecodescript" to "LiveCode Script",
        ".ls" to "LiveScript",
        "._ls" to "LiveScript",
        ".lgt" to "Logtalk",
        ".logtalk" to "Logtalk",
        ".lkml" to "LookML",
        ".lookml" to "LookML",
        ".lua" to "Lua",
        ".fcgi" to "Shell",
        ".nse" to "Lua",
        ".p8" to "Lua",
        ".pd_lua" to "Lua",
        ".rbxs" to "Lua",
        ".rockspec" to "Lua",
        ".wlua" to "Lua",
        ".luau" to "Luau",
        ".matlab" to "MATLAB",
        ".m" to "Objective-C",
        ".ms" to "MAXScript",
        ".mcr" to "MAXScript",
        ".mlir" to "MLIR",
        ".mq4" to "MQL4",
        ".mqh" to "MQL5",
        ".mq5" to "MQL5",
        ".m2" to "Macaulay2",
        ".mak" to "Makefile",
        ".make" to "Makefile",
        ".makefile" to "Makefile",
        ".mk" to "Makefile",
        ".mkfile" to "Makefile",
        ".mako" to "Mako",
        ".mao" to "Mako",
        ".mathematica" to "Mathematica",
        ".cdf" to "Mathematica",
        ".ma" to "Mathematica",
        ".mt" to "Mathematica",
        ".nb" to "Mathematica",
        ".nbp" to "Mathematica",
        ".wl" to "Mathematica",
        ".wlt" to "Mathematica",
        ".maxpat" to "Max",
        ".maxhelp" to "Max",
        ".maxproj" to "Max",
        ".mxt" to "Max",
        ".pat" to "Max",
        ".moo" to "Mercury",
        ".metal" to "Metal",
        ".mint" to "Mint",
        ".druby" to "Mirah",
        ".duby" to "Mirah",
        ".mirah" to "Mirah",
        ".mo" to "Motoko",
        ".i3" to "Modula-3",
        ".ig" to "Modula-3",
        ".m3" to "Modula-3",
        ".mg" to "Modula-3",
        ".mojo" to "Mojo",
        ".mc" to "Monkey C",
        ".moon" to "MoonScript",
        ".s" to "Motorola 68K Assembly",
        ".x68" to "Motorola 68K Assembly",
        ".move" to "Move",
        ".ncl" to "NCL",
        ".nss" to "NWScript",
        ".ne" to "Nearley",
        ".nearley" to "Nearley",
        ".n" to "Nemerle",
        ".axs" to "NetLinx",
        ".axi" to "NetLinx",
        ".axs.erb" to "NetLinx+ERB",
        ".axi.erb" to "NetLinx+ERB",
        ".nlogo" to "NetLogo",
        ".nl" to "NewLisp",
        ".nf" to "Nextflow",
        ".nim" to "Nim",
        ".nim.cfg" to "Nim",
        ".nimble" to "Nim",
        ".nimrod" to "Nim",
        ".nims" to "Nim",
        ".nit" to "Nit",
        ".nix" to "Nix",
        ".nr" to "Noir",
        ".nu" to "Nushell",
        ".numpy" to "NumPy",
        ".numpyw" to "NumPy",
        ".numsc" to "NumPy",
        ".ml" to "Standard ML",
        ".eliom" to "OCaml",
        ".eliomi" to "OCaml",
        ".ml4" to "OCaml",
        ".mli" to "OCaml",
        ".mll" to "OCaml",
        ".mly" to "OCaml",
        ".mm" to "Objective-C++",
        ".sj" to "Objective-J",
        ".odin" to "Odin",
        ".omgrofl" to "Omgrofl",
        ".opal" to "Opal",
        ".rego" to "Open Policy Agent",
        ".opencl" to "OpenCL",
        ".qasm" to "OpenQASM",
        ".scad" to "OpenSCAD",
        ".oxygene" to "Oxygene",
        ".oz" to "Oz",
        ".p4" to "P4",
        ".pddl" to "PDDL",
        ".pegjs" to "PEG.js",
        ".peggy" to "PEG.js",
        ".aw" to "PHP",
        ".ctp" to "PHP",
        ".php3" to "PHP",
        ".php4" to "PHP",
        ".php5" to "PHP",
        ".phps" to "PHP",
        ".phpt" to "PHP",
        ".pls" to "PLSQL",
        ".bdy" to "PLSQL",
        ".ddl" to "PLSQL",
        ".fnc" to "PLSQL",
        ".pck" to "PLSQL",
        ".pkb" to "PLSQL",
        ".pks" to "PLSQL",
        ".plb" to "PLSQL",
        ".plsql" to "PLSQL",
        ".prc" to "PLSQL",
        ".spc" to "PLSQL",
        ".sql" to "TSQL",
        ".tpb" to "PLSQL",
        ".tps" to "PLSQL",
        ".trg" to "PLSQL",
        ".vw" to "PLSQL",
        ".pgsql" to "PLpgSQL",
        ".pov" to "POV-Ray SDL",
        ".pact" to "Pact",
        ".pan" to "Pan",
        ".psc" to "Papyrus",
        ".parrot" to "Parrot",
        ".pas" to "Pascal",
        ".dfm" to "Pascal",
        ".dpr" to "Pascal",
        ".lpr" to "Pascal",
        ".pascal" to "Pascal",
        ".pp" to "Puppet",
        ".pwn" to "Pawn",
        ".sma" to "Pawn",
        ".pep" to "Pep8",
        ".pl" to "Raku",
        ".cgi" to "Shell",
        ".perl" to "Perl",
        ".ph" to "Perl",
        ".plx" to "Perl",
        ".pm" to "Raku",
        ".psgi" to "Perl",
        ".t" to "Turing",
        ".pig" to "PigLatin",
        ".pike" to "Pike",
        ".pmod" to "Pike",
        ".pkl" to "Pkl",
        ".pogo" to "PogoScript",
        ".polar" to "Polar",
        ".por" to "Portugol",
        ".pbt" to "PowerBuilder",
        ".sra" to "PowerBuilder",
        ".sru" to "PowerBuilder",
        ".srw" to "PowerBuilder",
        ".ps1" to "PowerShell",
        ".psd1" to "PowerShell",
        ".psm1" to "PowerShell",
        ".praat" to "Praat",
        ".pde" to "Processing",
        ".prolog" to "Prolog",
        ".yap" to "Prolog",
        ".pml" to "Promela",
        ".spin" to "Propeller Spin",
        ".pb" to "PureBasic",
        ".pbi" to "PureBasic",
        ".purs" to "PureScript",
        ".arr" to "Pyret",
        ".py" to "Python",
        ".gyp" to "Python",
        ".gypi" to "Python",
        ".lmi" to "Python",
        ".py3" to "Python",
        ".pyde" to "Python",
        ".pyi" to "Python",
        ".pyp" to "Python",
        ".pyt" to "Python",
        ".pyw" to "Python",
        ".rpy" to "Ren'Py",
        ".spec" to "Ruby",
        ".tac" to "Python",
        ".wsgi" to "Python",
        ".xpy" to "Python",
        ".qs" to "Qt Script",
        ".qml" to "QML",
        ".qbs" to "QML",
        ".r" to "Rez",
        ".rd" to "R",
        ".rsx" to "R",
        ".rexx" to "REXX",
        ".pprx" to "REXX",
        ".rex" to "REXX",
        ".rpgle" to "RPGLE",
        ".sqlrpgle" to "RPGLE",
        ".rkt" to "Racket",
        ".rktd" to "Racket",
        ".rktl" to "Racket",
        ".scrbl" to "Racket",
        ".rl" to "Ragel",
        ".6pl" to "Raku",
        ".6pm" to "Raku",
        ".nqp" to "Raku",
        ".p6" to "Raku",
        ".p6l" to "Raku",
        ".p6m" to "Raku",
        ".pl6" to "Raku",
        ".pm6" to "Raku",
        ".raku" to "Raku",
        ".rakumod" to "Raku",
        ".rsc" to "RouterOS Script",
        ".res" to "ReScript",
        ".rei" to "Reason",
        ".religo" to "ReasonLIGO",
        ".reb" to "Rebol",
        ".r2" to "Rebol",
        ".r3" to "Rebol",
        ".rebol" to "Rebol",
        ".red" to "Red",
        ".reds" to "Red",
        ".ring" to "Ring",
        ".robot" to "RobotFramework",
        ".roc" to "Roc",
        ".rg" to "Rouge",
        ".rb" to "Ruby",
        ".builder" to "Ruby",
        ".eye" to "Ruby",
        ".gemspec" to "Ruby",
        ".god" to "Ruby",
        ".jbuilder" to "Ruby",
        ".mspec" to "Ruby",
        ".pluginspec" to "Ruby",
        ".podspec" to "Ruby",
        ".prawn" to "Ruby",
        ".rabl" to "Ruby",
        ".rake" to "Ruby",
        ".rbi" to "Ruby",
        ".rbuild" to "Ruby",
        ".rbw" to "Ruby",
        ".rbx" to "Ruby",
        ".ru" to "Ruby",
        ".ruby" to "Ruby",
        ".thor" to "Ruby",
        ".watchr" to "Ruby",
        ".rs" to "Rust",
        ".rs.in" to "Rust",
        ".sas" to "SAS",
        ".sqf" to "SQF",
        ".hqf" to "SQF",
        ".db2" to "SQLPL",
        ".sls" to "Scheme",
        ".scala" to "Scala",
        ".kojo" to "Scala",
        ".sbt" to "Scala",
        ".sc" to "SuperCollider",
        ".scenic" to "Scenic",
        ".scm" to "Scheme",
        ".sch" to "Scheme",
        ".sld" to "Scheme",
        ".sps" to "Scheme",
        ".ss" to "Scheme",
        ".sci" to "Scilab",
        ".sce" to "Scilab",
        ".self" to "Self",
        ".sh" to "Shell",
        ".bash" to "Shell",
        ".bats" to "Shell",
        ".command" to "Shell",
        ".ksh" to "Shell",
        ".sh.in" to "Shell",
        ".tmux" to "Shell",
        ".tool" to "Shell",
        ".zsh" to "Shell",
        ".zsh-theme" to "Shell",
        ".shen" to "Shen",
        ".sl" to "Slash",
        ".ice" to "Slice",
        ".cocci" to "SmPL",
        ".st" to "Smalltalk",
        ".tpl" to "Smarty",
        ".smithy" to "Smithy",
        ".smk" to "Snakemake",
        ".snakefile" to "Snakemake",
        ".sol" to "Solidity",
        ".sp" to "SourcePawn",
        ".nut" to "Squirrel",
        ".stan" to "Stan",
        ".fun" to "Standard ML",
        ".sig" to "Standard ML",
        ".sml" to "Standard ML",
        ".bzl" to "Starlark",
        ".star" to "Starlark",
        ".do" to "Stata",
        ".ado" to "Stata",
        ".doh" to "Stata",
        ".ihlp" to "Stata",
        ".mata" to "Stata",
        ".matah" to "Stata",
        ".sthlp" to "Stata",
        ".scd" to "SuperCollider",
        ".sw" to "Sway",
        ".swift" to "Swift",
        ".sv" to "SystemVerilog",
        ".svh" to "SystemVerilog",
        ".vh" to "SystemVerilog",
        ".8xp" to "TI Program",
        ".8xp.txt" to "TI Program",
        ".tlv" to "TL-Verilog",
        ".tla" to "TLA",
        ".tsx" to "TSX",
        ".txl" to "TXL",
        ".talon" to "Talon",
        ".tcl" to "Tcl",
        ".adp" to "Tcl",
        ".sdc" to "Tcl",
        ".tcl.in" to "Tcl",
        ".tm" to "Tcl",
        ".xdc" to "Tcl",
        ".thrift" to "Thrift",
        ".toit" to "Toit",
        ".tu" to "Turing",
        ".ts" to "TypeScript",
        ".cts" to "TypeScript",
        ".mts" to "TypeScript",
        ".typ" to "Typst",
        ".upc" to "Unified Parallel C",
        ".uno" to "Uno",
        ".uc" to "UnrealScript",
        ".ur" to "UrWeb",
        ".urs" to "UrWeb",
        ".frm" to "Visual Basic 6.0",
        ".vba" to "Vim Script",
        ".vbs" to "VBScript",
        ".vcl" to "VCL",
        ".vhdl" to "VHDL",
        ".vhd" to "VHDL",
        ".vhf" to "VHDL",
        ".vhi" to "VHDL",
        ".vho" to "VHDL",
        ".vhs" to "VHDL",
        ".vht" to "VHDL",
        ".vhw" to "VHDL",
        ".vala" to "Vala",
        ".vapi" to "Vala",
        ".veo" to "Verilog",
        ".vim" to "Vim Script",
        ".vimrc" to "Vim Script",
        ".vmb" to "Vim Script",
        ".vb" to "Visual Basic .NET",
        ".vbhtml" to "Visual Basic .NET",
        ".ctl" to "Visual Basic 6.0",
        ".Dsr" to "Visual Basic 6.0",
        ".volt" to "Volt",
        ".vy" to "Vyper",
        ".wdl" to "WDL",
        ".wgsl" to "WGSL",
        ".wast" to "WebAssembly",
        ".wat" to "WebAssembly",
        ".whiley" to "Whiley",
        ".ws" to "Witcher Script",
        ".wlk" to "Wollok",
        ".wren" to "Wren",
        ".x10" to "X10",
        ".xc" to "XC",
        ".xquery" to "XQuery",
        ".xq" to "XQuery",
        ".xql" to "XQuery",
        ".xqm" to "XQuery",
        ".xqy" to "XQuery",
        ".xslt" to "XSLT",
        ".xsl" to "XSLT",
        ".xojo_code" to "Xojo",
        ".xojo_menu" to "Xojo",
        ".xojo_report" to "Xojo",
        ".xojo_script" to "Xojo",
        ".xojo_toolbar" to "Xojo",
        ".xojo_window" to "Xojo",
        ".xsh" to "Xonsh",
        ".xtend" to "Xtend",
        ".yar" to "YARA",
        ".yara" to "YARA",
        ".y" to "Yacc",
        ".yacc" to "Yacc",
        ".yy" to "Yacc",
        ".yul" to "Yul",
        ".zap" to "ZAP",
        ".xzap" to "ZAP",
        ".zil" to "ZIL",
        ".mud" to "ZIL",
        ".zs" to "ZenScript",
        ".zep" to "Zephir",
        ".zig" to "Zig",
        ".zig.zon" to "Zig",
        ".zimpl" to "Zimpl",
        ".zmpl" to "Zimpl",
        ".zpl" to "Zimpl",
        ".ec" to "eC",
        ".eh" to "eC",
        ".fish" to "fish",
        ".hoon" to "hoon",
        ".mrc" to "mIRC Script",
        ".mcfunction" to "mcfunction",
        ".mu" to "mupad",
        ".nc" to "nesC",
        ".ooc" to "ooc",
        ".sed" to "sed",
        ".wisp" to "wisp",
        ".prg" to "xBase",
        ".ch" to "xBase",
        ".prw" to "xBase",
    )
}
